package me.kvait.exception

class UserExistsException(message: String) : RuntimeException(message)